### ISSUE TITLE
[API USER AUTHEMTICATION] Grant only authenticated users to  access the API

### ISSUE THREAD

**Issue by Nataanthoni** [BuildForSDG/PulaniBack#12]
**Description:** This task involves implementing Pulani API authentication. Only authenticated users should be allowed to access the Pulani data. 

**Acceptance Criteria:**
- Fully functional login via authentication using email and password
- Install and configure JWT(JSON Web Token) to auto generate tokens to be passed whenever fetching data.
- Develop and publicize Authentication API documentation

**Comment by samuelokellogum** [comment]
Shouldn't authentication be using phone number and password as suggested by front end team? I am confused now

**Comment by Nataanthoni** [comment]
Yes it should. If you look at this issue, you will realize the purpose is to let someone follow the steps taken by the Backend guys. The modification of allowing users log in with phone just improves this task. Hope this is clear.

**Comment by Nataanthoni** [comment]
This was already fixed.
